services:
  postgres:
    image: postgres:13
    container_name: postgres-notes-manager
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: defaultdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis-notes-manager
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: api-concert
  #   environment:
  #     DATABASE_URL: postgresql://admin:admin@postgres:5432/defaultdb
  #   depends_on:
  #     - postgres
  #   ports:
  #     - '5000:5000'
  #   command: sh -c "npx prisma migrate dev && node dist/main.js"

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
